sudo: requied 
arch: amd64
os: linux
dist: focal
language: node_js
services :
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t multi-docker .

script:
  - docker run multi-docker npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  # Login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker tag  multi-client ganesh/multi-client
  - docker push multi-client 
  - docker tag  multi-nginx
  - docker push multi-nginx
  - docker tag  multi-server
  - docker push multi-server
  - docker tag  multi-worker
  - docker push multi-worker

