sudo: requied 
arch: amd64
os: linux
dist: focal
language: node_js
services :
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t multi-docker .

script:
  - docker run multi-docker npm test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  # Login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub . Tag the image before pushing to hub
  - docker tag  multi-client ganeshnikam29/multi-client
  - docker push ganeshnikam29/multi-client 
  - docker tag  multi-nginx ganeshnikam29/multi-nginx
  - docker push ganeshnikam29/multi-nginx
  - docker tag  multi-server ganeshnikam29/multi-server
  - docker push ganeshnikam29/multi-server
  - docker tag  multi-worker ganeshnikam29/multi-worker
  - docker push  ganeshnikam29/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi_container_docker"
  env: "Multicontainerdocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-193166174810"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
     secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
