version: '3'
services: 
    postgres:
      image : 'postgres:latest'
      ports: 
        - "5432:5432"
      environment: 
        - POSTGRES_USER=root
        - POSTGRES_DB=postgres
        - POSTGRES_HOST=localhost
        - POSTGRES_PASSWORD=root
        - POSTGRES_PORT=5432
    redis:
      image: 'redis:latest'
      environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      ports: 
        - "6379:6379"
    api:
      build: 
        dockerfile: Dockerfile.dev
        context: ./server
      expose:
        - 5000
      ports:
        - "5000:5000"
      volumes: 
        - /app/node_modules
        - ./server:/app  
      networks:
          - u-online
    client:
        build: 
          dockerfile: Dockerfile.dev
          context: ./client
        expose:
          - 3000
        ports:
          - "3000:3000"
        volumes: 
          - /app/node_modules
          - ./client:/app
        networks:
          - u-online
    nginx:
        restart: always
        depends_on: 
          - api
          - client
        build: 
          dockerfile: Dockerfile.dev
          context: ./nginx
        expose:
          - 80
        ports: 
          - '3050:80'
        networks:
          - u-online
    worker:
        build: 
          dockerfile: Dockerfile.dev
          context: ./worker
        volumes: 
          - /app/node_modules
          - ./worker:/app
        networks:
          - u-online
networks:
  u-online:
    driver: bridge
volumes: 
  server:
  client:
